/**
 * Created by Kostadinovska Stefani on 18/08/2016.
 */

$(document).ready(function () {

    $(".subParagraphs").hide();
    $(".intro").hide();
    $(".conds").hide();
    $(".insta").hide();
    $(".safe").hide();
    $(".extraDiv2").hide();
    $(".extraDiv3").hide();
    $(".extraDiv4").hide();
    $(".aboutUs").hide();
    $(".bancomats").hide();
    $(".cell").show();
    $(".network").hide();
    $(".currency").hide();
    $(".creditCards").hide();
    $(".notifications").hide();
    $(".myTrans").hide();
    $(".devizniSmetki").hide();
    $(".tekovniSmetki").hide();
    $(".extraDiv6").hide();
    $(".extraDiv7").hide();
    $(".extraDiv8").hide();
    $(".kreditniKartichki").hide();
    $(".denarskiKniski").hide();
    $(".devizniKniski").hide();
    $(".credit").hide();
    $(".limitCards").hide();
    $(".limitDevices").hide();
    $(".leftMenu").hide();
    $(".myData").hide();
    $(".activation").hide();



    $(".mainMenu").hover(function () {
        $(".subParagraphs").show();

    });

    $(".mainMenu").click(function () {
        $(".subParagraphs").hide();
    });

    $(".logoPicture").click(function(){
        $(".intro").hide();
        $(".conds").hide();
        $(".text").show();
        $(".insta").hide();
        $(".safe").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".aboutUs").hide();
        $(".bancomats").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });


    $(".introduction").click(function () {
        $(".intro").show();
        $(".conds").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".safe").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".aboutUs").hide();
        $(".bancomats").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $('.conditions').click(function () {
        $(".conds").show();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".safe").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".aboutUs").hide();
        $(".bancomats").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".instalation").click(function () {
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").show();
        $(".safe").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".aboutUs").hide();
        $(".bancomats").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".safety").click(function () {
        $(".safe").show();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".extraDiv2").show();
        $(".extraDiv3").show();
        $(".extraDiv4").show();
        $(".aboutUs").hide();
        $(".bancomats").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".contact").click(function () {
        $(".aboutUs").show();
        $(".intro").hide();
        $(".conds").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".safe").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".bancomats").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });


    $(".ban").click(function () {
        $(".bancomats").show();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".net").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").show();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".cur").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").show();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".cards").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").show();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".not").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").show();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".tran").click(function () {
        $(".myTrans").show();
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".devizni").click(function () {
        $(".myTrans").hide();
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".devizniSmetki").show();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".tekovni").click(function () {
        $(".myTrans").hide();
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").show();
        $(".extraDiv7").show();
        $(".extraDiv6").show();
        $(".extraDiv8").show();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".kreditni").click(function () {
        $(".myTrans").hide();
        $(".bancomats").hide();
        $(".extraDiv2").show();
        $(".extraDiv3").show();
        $(".extraDiv4").show();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").show();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".denKniski").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").show();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".devKniski").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").show();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".cre").click(function () {
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").show();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".limKartici").click(function(){
        $(".bancomats").hide();
        $(".extraDiv2").show();
        $(".extraDiv3").show();
        $(".extraDiv4").show();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").show();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();


    });

    $(".limUred").click(function(){
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").show();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").show();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".desno").click(function(){
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").show();
        $(".myData").hide();
        $(".activation").hide();

    });

    $(".data").click(function(){
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").hide();
        $(".extraDiv7").hide();
        $(".extraDiv8").hide();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").show();
        $(".activation").hide();

    });

    $(".reg").click(function(){
        $(".bancomats").hide();
        $(".extraDiv2").hide();
        $(".extraDiv3").hide();
        $(".extraDiv4").hide();
        $(".conds").hide();
        $(".intro").hide();
        $(".text").hide();
        $(".insta").hide();
        $(".aboutUs").hide();
        $(".safe").hide();
        $(".cell").hide();
        $(".network").hide();
        $(".currency").hide();
        $(".creditCards").hide();
        $(".notifications").hide();
        $(".myTrans").hide();
        $(".devizniSmetki").hide();
        $(".tekovniSmetki").hide();
        $(".extraDiv6").show();
        $(".extraDiv7").show();
        $(".extraDiv8").show();
        $(".kreditniKartichki").hide();
        $(".denarskiKniski").hide();
        $(".devizniKniski").hide();
        $(".credit").hide();
        $(".limitCards").hide();
        $(".limitDevices").hide();
        $(".leftMenu").hide();
        $(".myData").hide();
        $(".activation").show();
    })

});